config/routes.rb
Rails.application.routes.draw do
  root "application#home"
  resources :users
  resources :books
  resources :categories
  resources :reviews
  resources :relationships
  resources :ratings
  resources :comments
  resources :requests
  resources :activities, only: [:new,:create,:destroy]
  resources :likes, only: [:destroy]
  get "logout" => "sessions#destroy"
  get "login" => "sessions#new"
  get "actives" => "activities#create"
  get "logs" => "activities#actives_log"
  get "likes" => "likes#create"
  post "logs" => "activities#find_log"
  post "login" => "sessions#create"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/activity.rb
class Activity < ApplicationRecord
  belongs_to :user
  belongs_to :target, polymorphic: true
  has_many :likes, as: :target
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :category
  mount_uploader :image, ImageUploader
  has_attached_file :image, styles: {medium: "300x300>", thumb: "100x100>"}
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
  has_many :activities, as: :target
  has_many :reviews, dependent: :destroy
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :books, dependent: :destroy
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :target, polymorphic: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :target, polymorphic: true
  validates_uniqueness_of :target_id, :scope => :user_id
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: User.name
  belongs_to :followed, class_name: User.name
end

app/models/request.rb
class Request < ApplicationRecord
  belongs_to :user
  before_save { self.status =false }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :book
  belongs_to :user, dependent: :destroy
  has_many :comments, as: :target
end

app/models/user.rb
class User < ApplicationRecord
	has_many :reviews, dependent: :destroy
	has_many :activities, dependent: :destroy
	has_many :requests, dependent: :destroy
	has_many :comments, dependent: :destroy
	has_many :relationships, through: :active_relationships, source: :followed
	has_many :active_relationships, class_name: :Relationship.name,
    foreign_key: :follower_id, dependent: :destroy
	has_many :passive_relationships, class_name: :Relationship.name,
    foreign_key: :followed_id, dependent: :destroy
	has_many :following, through: :active_relationships, source: :followed
	before_save {self.email = email.downcase}
	has_secure_password
	validates :password,presence: true,length: {minimum: 6, allow_blank: true}
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, length: { maximum: 100 },
	format: {with: VALID_EMAIL_REGEX},uniqueness: {case_sensitive: false}
	VALID_FULLNAME_REGEX = /[\w]+([\s]+[\w]+){1}+/
	validates :fullname,presence: true, length: {maximum:150},
	format: {with: VALID_FULLNAME_REGEX}

  def follow(other_user)
  	active_relationships.create(followed_id: other_user.id)
  end

  def unfollow(other_user)
  	active_relationships.find_by(followed_id: other_user.id).destroy
  end

  def count_fl
  	active_relationships.find_by(followed_id: other_user.id).count
  end

  def following?(other_user)
  	following.include?(other_user)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :book_load, only: [:index, :edit, :update, :destroy ]

  def index
    @books=Book.paginate page: params[:page],per_page: Settings.ten
  end

  def show
    @book=book_load
    @reviews=@book.review
    @rating=@book.rating
  end

  def new
    @categories=Category.all
  end

  def create
    book = Book.new book_params
    if book.save
      flash[:success] = t "success_create"
      redirect_to books_path
    else
      flash[:info] = t "error_create"
      render "new"
    end
  end

  def edit
    @book = book_load
  end

  def update
    book = book_load
    if book.update_attributes(book_params)
      flash[:success] = t "update_success"
      redirect_to books_path
    else
      flash[:error] = t "update_error"
      render :back
    end
  end

  def destroy
    book_load.destroy
    flash[:success] = t "delete_success"
    redirect_to books_path
  end

  private
  def book_params
    params.require(:book).permit(:title,:publish_date,:author,:num_of_page,:category_id,:image,rating:0)
  end

  def book_load
    book = Book.find_by params[:id]
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  skip_before_filter :verify_authenticity_token

  def index

  end

  def new

  end

  def create
    @comment = Comment.new(comment_params)
    @review = params[:comment][:target_id]
    if @comment.save
      respond_to do |format|
        format.html {redirect_to @review}
        format.js
      end
    else
      flash[:info] = "Error for Create!"
    end
  end

  def show
    @comment=comment_load
    @reviews=@comment.review
  end

  def update

  end

  def edit

  end

  def destroy
    comment_load.destroy
    redirect_to :back
  end

  private
  def comment_params
    params.require(:comment).permit(:target_id,:content,:parent_id).merge!(user_id:current_user.id,target_type:"Review")
  end

  def comment_load
    comment = Comment.find(params[:id])
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    if active_like=Like.new(target_id:params[:id],target_type:"Activity",user_id:current_user.id).save
      @user =User.find(params[:user_id])
      respond_to do |format|
        format.js
      end
    end
  end

  def destroy
    active_like=Like.where(target_id:params[:id],user_id:current_user.id).first.destroy
    @user =User.find(params[:user_id])
    respond_to do |format|
      format.js
    end
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
  def check_rate book_id,condition
    active=Activity.where(user_id:current_user.id,target_id:book_id,action:condition)
    return active.any?
  end

  def avg_rating book_id
    return count_rating=Activity.where(action: t("rating"),target_id:book_id,target_type:"book").count+1
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
  def like target_id,user_id
    return Like.where(target_id:target_id,user_id:user_id).any?
  end

  def toggle_like_button(activity,user)
    if Like.where(target_id:activity.id,user_id:current_user.id).any?
      link_to " DisLike",like_path(id:activity.id,user_id:user.id),method: "delete",remote:true,class: "fa fa-thumbs-o-down",id:"dis#{activity.id}"
    else
      link_to " Like",likes_path(id:activity.id,user_id:user.id),remote:true,class: "fa fa-thumbs-o-up",id:"like#{activity.id}"
    end
  end
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
  def Request_Toggle request
    unless current_user.is_admin
      unless request.status
        link_to t("cancel"), request_path(id:request.id), method: "delete",
          class: "fa fa-check",data: {confirm: t("confirm")}
      end
    end
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def user_login user
    session[:user_id] = user.id
  end

  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find(user_id)
    end
  end

  def login?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  def is_admin?
    return current_user.is_admin
  end
end

app/helpers/users_helper.rb
module UsersHelper
	# Returns the Gravatar for the given user.
	def gravatar_for human,size=200
		gravatar_id = Digest::MD5::hexdigest(human.email.downcase)
		gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
		image_tag(gravatar_url, alt: human.fullname, class: "gravatar")
	end
end

app/views/comments/_comment.html.erb
<div id="comment-<%= comment.id %>">
  <div class="code-in">
    <%= gravatar_for comment.user,40 %>
    <p class="smith"><a href="#"><i class="glyphicon glyphicon-user">
      </i> <%= comment.user.fullname %></a>
      <span class="date">
        <%= time_ago_in_words(comment.created_at) %><%= t "ago" %>
      </span>
    </p>
    <div class="clearfix"> </div>
  </div>
  <div class="media-body">
    <p><%= comment.content %></p>
  </div>
  <div >
    <% if current_user == comment.user %>
      <%= link_to "", edit_comment_path(comment),
        class: "glyphicon glyphicon-edit", id: "comment-#{comment.id}", remote: true %>
      <%= link_to "", comment_path(comment), method: :delete,
        data: {confirm: t("confirm_delete")}, class: "glyphicon glyphicon-trash text-danger",
         remote: true %>
    <% end %>
  </div>
  <hr />
</div>

app/views/comments/_form.html.erb
<% if login? %>
<div class="comment_detail">
		<%= form_for(Comment.new,remote: true) do |f| %>
		<%= render 'shared/error_messages', object: f.object %>
		<div class="form-group">
			<%= f.hidden_field :target_id, value: 15 %>
			<%= f.hidden_field :parent_id, value: 0 %>
		</div>
		<div class="form-group">
			<%= f.text_area :content, placeholder: "Comment here!!!",id: "parent_cmt"%>
			<button type="submit" class="btn btn-submit" >Comment</button>
		</div>
		<% end %>
</div>
<% end %>

app/views/comments/_list_comment.html.erb
<% @review.comments.each do |item|%>
<div class="cmttext">
  <%= gravatar_for item.user,40 %>
  <b><%= item.user.fullname %></b>:
  <%= text_area :comment,:content,:value=> item.content,id: "text_area",:disabled => true %>
  <i>(<%= time_ago_in_words(item.created_at) %>)</i>
  <%= link_to "","javascript:void(0)",class: "fa fa-pencil",id: "editcmt" %>
  <%= link_to "",comment_path(item.id),method: "delete",class: "fa fa-times" %><br>
  <div class="action_cmt">
    <%= link_to "Like","javascript:void(0)",id: "like" %>
    <%= link_to "Reply","javascript:void(0)",class: "reply", id: item.id, review_id: @review.id %>
  </div>
</div>
<div class="chird_cmt"></div>
<br>
<%= render "comments/reply" %>
<hr>
<% end %>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
<script type="text/javascript">
    var aa = document.getElementById('text_area');
  $("editcmt")[0].click(function() {
    alert(1);

  });
</script>

app/views/comments/_reply.html.erb
<div class="replyform"></div>
<script type="text/javascript">
	var cmt_id;
	var review_id;
	var allArea =document.getElementsByClassName("rl_cmt");
	var allElements = document.getElementsByClassName("reply");
	var addCommentField = function() {
		for (var i = 0; allElements.length > i; i++) {
			if (allElements[i] === this) {
				var cmt_id=this.getAttribute("id");
				var review_id=this.getAttribute("review_id");

				if (document.getElementsByClassName("replyform")[i].innerHTML.length === 0) {
					document.getElementsByClassName("replyform")[i].innerHTML = "<form method='post' action='/comments' data-remote='true' ><textarea class='rl_cmt' name='comment[content]'autofocus ></textarea><input type='hidden' name='comment[parent_id]' value='"+cmt_id+"'/><input type='hidden' name='comment[target_id]' value='"+review_id+"'/> <input type='submit' id='btn_rep' class='btn btn-submit' onclick('checkcmt();')/> </form>";
				}
			}
		}
	};
	for (var i = 0; i < allElements.length; i++) {
		allElements[i].addEventListener('click', addCommentField, false);
	}



</script>
<script type="text/javascript">
	function checkcmt(){
		console.log($(".rl_cmt"));
	}

</script>

app/views/comments/create.js.erb
var comments_list = $('#comments-list');
comments_list.prepend('<%= j render @comment %>');

app/views/comments/edit.html.erb
<h1>Comments#edit</h1>
<p>Find me in app/views/comments/edit.html.erb</p>

app/views/comments/error.js.erb
<% @comment.errors.full_messages.each do |message| %>
  console.log("<%= message %>");
<% end %>