config/routes.rb
Rails.application.routes.draw do
  root "application#home"
  resources :users
  resources :books
  resources :categories
  resources :reviews
  resources :relationships
  resources :ratings
  resources :comments
  resources :requests
  resources :activities, only: [:new,:create,:destroy]
  resources :likes, only: [:destroy]
  get "logout" => "sessions#destroy"
  get "login" => "sessions#new"
  get "actives" => "activities#create"
  get "logs" => "activities#actives_log"
  get "likes" => "likes#create"
  post "logs" => "activities#find_log"
  post "login" => "sessions#create"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/activity.rb
class Activity < ApplicationRecord
  belongs_to :user
  belongs_to :target, polymorphic: true
  has_many :likes, as: :target
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :category
  mount_uploader :image, ImageUploader
  has_attached_file :image, styles: {medium: "300x300>", thumb: "100x100>"}
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
  has_many :activities, as: :target
  has_many :reviews, dependent: :destroy
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :books, dependent: :destroy
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :target, polymorphic: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :target, polymorphic: true
  validates_uniqueness_of :target_id, :scope => :user_id
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: User.name
  belongs_to :followed, class_name: User.name
end

app/models/request.rb
class Request < ApplicationRecord
  belongs_to :user
  before_save { self.status =false }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :book
  belongs_to :user, dependent: :destroy
  has_many :comments, as: :target
end

app/models/user.rb
class User < ApplicationRecord
	has_many :reviews, dependent: :destroy
	has_many :activities, dependent: :destroy
	has_many :requests, dependent: :destroy
	has_many :comments, dependent: :destroy
	has_many :relationships, through: :active_relationships, source: :followed
	has_many :active_relationships, class_name: :Relationship.name,
    foreign_key: :follower_id, dependent: :destroy
	has_many :passive_relationships, class_name: :Relationship.name,
    foreign_key: :followed_id, dependent: :destroy
	has_many :following, through: :active_relationships, source: :followed
	before_save {self.email = email.downcase}
	has_secure_password
	validates :password,presence: true,length: {minimum: 6, allow_blank: true}
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, length: { maximum: 100 },
	format: {with: VALID_EMAIL_REGEX},uniqueness: {case_sensitive: false}
	VALID_FULLNAME_REGEX = /[\w]+([\s]+[\w]+){1}+/
	validates :fullname,presence: true, length: {maximum:150},
	format: {with: VALID_FULLNAME_REGEX}

  def follow(other_user)
  	active_relationships.create(followed_id: other_user.id)
  end

  def unfollow(other_user)
  	active_relationships.find_by(followed_id: other_user.id).destroy
  end

  def count_fl
  	active_relationships.find_by(followed_id: other_user.id).count
  end

  def following?(other_user)
  	following.include?(other_user)
  end
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  def create
    key=params[:key]
    book_id=params[:book_id]
    activity=Activity.create(action:key,target_id:book_id,target_type:"Book",user_id:current_user.id)
  end

  def actives_log
    @hash_select=[{:value=>"Filter by Reading", :key=>"Reading"},{:value=>"Filter by Readed",:key=>"Readed"},{:value=>"Filter by Favorite",:key=>"Favorite"}]
  end

  def find_log
    condition="%#{params[:log][:condition]}%"
    @logs=Activity.where("action like ? ",condition).paginate(page: params[:page],per_page: 10)
    respond_to do |format|
      format.js
    end
  end

  def destroy
    activity = Activity.find(params[:id]).destroy
    respond_to do |format|
      format.js
    end
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :book_load, only: [:index, :edit, :update, :destroy ]

  def index
    @books=Book.paginate page: params[:page],per_page: Settings.ten
  end

  def show
    @book=book_load
    @reviews=@book.review
    @rating=@book.rating
  end

  def new
    @categories=Category.all
  end

  def create
    book = Book.new book_params
    if book.save
      flash[:success] = t "success_create"
      redirect_to books_path
    else
      flash[:info] = t "error_create"
      render "new"
    end
  end

  def edit
    @book = book_load
  end

  def update
    book = book_load
    if book.update_attributes(book_params)
      flash[:success] = t "update_success"
      redirect_to books_path
    else
      flash[:error] = t "update_error"
      render :back
    end
  end

  def destroy
    book_load.destroy
    flash[:success] = t "delete_success"
    redirect_to books_path
  end

  private
  def book_params
    params.require(:book).permit(:title,:publish_date,:author,:num_of_page,:category_id,:image,rating:0)
  end

  def book_load
    book = Book.find_by params[:id]
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    if active_like=Like.new(target_id:params[:id],target_type:"Activity",user_id:current_user.id).save
      @user =User.find(params[:user_id])
      respond_to do |format|
        format.js
      end
    end
  end

  def destroy
    active_like=Like.where(target_id:params[:id],user_id:current_user.id).first.destroy
    @user =User.find(params[:user_id])
    respond_to do |format|
      format.js
    end
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
  def check_rate book_id,condition
    active=Activity.where(user_id:current_user.id,target_id:book_id,action:condition)
    return active.any?
  end

  def avg_rating book_id
    return count_rating=Activity.where(action: t("rating"),target_id:book_id,target_type:"book").count+1
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
  def like target_id,user_id
    return Like.where(target_id:target_id,user_id:user_id).any?
  end

  def toggle_like_button(activity,user)
    if Like.where(target_id:activity.id,user_id:current_user.id).any?
      link_to " DisLike",like_path(id:activity.id,user_id:user.id),method: "delete",remote:true,class: "fa fa-thumbs-o-down",id:"dis#{activity.id}"
    else
      link_to " Like",likes_path(id:activity.id,user_id:user.id),remote:true,class: "fa fa-thumbs-o-up",id:"like#{activity.id}"
    end
  end
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
  def Request_Toggle request
    unless current_user.is_admin
      unless request.status
        link_to t("cancel"), request_path(id:request.id), method: "delete",
          class: "fa fa-check",data: {confirm: t("confirm")}
      end
    end
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def user_login user
    session[:user_id] = user.id
  end

  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find(user_id)
    end
  end

  def login?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  def is_admin?
    return current_user.is_admin
  end
end

app/helpers/users_helper.rb
module UsersHelper
	# Returns the Gravatar for the given user.
	def gravatar_for human,size=200
		gravatar_id = Digest::MD5::hexdigest(human.email.downcase)
		gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
		image_tag(gravatar_url, alt: human.fullname, class: "gravatar")
	end
end

app/views/activities/_list_log.html.erb
<ul class="custom-servis-ul">
  <% if !@logs.nil? %>
  <% @logs.each do |l| %>
  <div id="log-<%=l.id %>">
    <%= link_to "",activity_path(l.id), class: "action cross",method: "delete", title: "Remove this actives?",:remote => true,data: { confirm: 'Are you sure?' }  %>
    <li class="item-1">
      <h3>You've been <%= l.action  %> the
        <%= l.target_type  %>: <%= link_to l.target.title,l.target %>
        (at <%=time_ago_in_words(l.target.created_at) %>)
      </h3>
      <div class="log_book">
        <%= image_tag l.target.image.url, :width => 120 %>
      </div>
      <ul class="log_details">
        <li>Title: <span><%= l.target.title  %></span></li>
        <li>Pushlish On: <span><%= l.target.publish_date %></span></li>
        <li>Author: <span><%= l.target.author %></span></li>
        <li>Num of pages: <span><%= l.target.num_of_page %></span></li>
      </ul>
    </li>
    <br>
  </div>
  <% end %>
  <% end %>
</ul>

app/views/activities/_list_log_user.html.erb
<div id="list_log">
  <ul class="custom-servis-ul">
    <h1>List log</h1><br>
      <% if !@user.activities.nil? %>
      <% @user.activities.each do |log| %>
        <div id="log-<%=log.id %>">
          <li class="item-1">
            <h3>
              <% if current_user.id!=@user.id %>
              <%= @user.fullname %>
              <% else %>
              You've
              <% end %> been add the Book: <%= link_to log.target.title,log.target %> on the list <%= log.action  %>
              (at <%=time_ago_in_words(log.target.created_at) %>)
            </h3>
          </li>
          <%= toggle_like_button log,@user %>
          (<%= log.likes.count %>)
          <% if current_user==@user %>
          <div class="space">|</div>
          <%= link_to " Delete",activity_path(log.id),method: "delete", title: "Remove this actives?",:remote => true,data: { confirm: 'Are you sure?' },class: "fa fa-times",id: "del_log"  %>
          <% end %>
        </div>
      <% end %>
      <% end %>
  </ul>
</div>

app/views/activities/actives_log.html.erb
<div class="inner_page">
  <div class="signup">
    <h1>Activity log</h1>
    <br>
    <div class="log_form">
      <%= form_for(logs_path, remote:true) do |f| %>
      <select name="log[condition]" id="select_log">
        <option value="%">All</option>
        <option value="Reading">Filter by Reading</option>
        <option value="Favorite">Filter by Favorite</option>
        <option value="Readed">Filter by Readed</option>
        <option value="Rating">Filter by Rating</option>
      </select>
      <%= f.submit :Submit, class: "btn btn-submit", id: "log_btn"%>
      <% end %>
    </div>
  </div>
</div>
<script type="text/javascript">
  $('select').select2();

</script>
<div id="list_log">

</div>

app/views/activities/destroy.js.erb
document.getElementById("log-<%=params[:id] %>").hide();

app/views/activities/find_log.js.erb
var htmlee ='<%= escape_javascript(render('activities/list_log')) %>';
jQuery("#list_log").html(htmlee);