config/routes.rb
Rails.application.routes.draw do
  root "application#home"
  resources :users
  resources :books
  resources :categories
  resources :reviews
  resources :relationships
  resources :ratings
  resources :comments
  resources :requests
  resources :activities, only: [:new,:create,:destroy]
  resources :likes, only: [:destroy]
  get "logout" => "sessions#destroy"
  get "login" => "sessions#new"
  get "actives" => "activities#create"
  get "logs" => "activities#actives_log"
  get "likes" => "likes#create"
  post "logs" => "activities#find_log"
  post "login" => "sessions#create"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/activity.rb
class Activity < ApplicationRecord
  belongs_to :user
  belongs_to :target, polymorphic: true
  has_many :likes, as: :target
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :category
  mount_uploader :image, ImageUploader
  has_attached_file :image, styles: {medium: "300x300>", thumb: "100x100>"}
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
  has_many :activities, as: :target
  has_many :reviews, dependent: :destroy
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :books, dependent: :destroy
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :target, polymorphic: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :target, polymorphic: true
  validates_uniqueness_of :target_id, :scope => :user_id
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: User.name
  belongs_to :followed, class_name: User.name
end

app/models/request.rb
class Request < ApplicationRecord
  belongs_to :user
  before_save { self.status =false }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :book
  belongs_to :user, dependent: :destroy
  has_many :comments, as: :target
end

app/models/user.rb
class User < ApplicationRecord
	has_many :reviews, dependent: :destroy
	has_many :activities, dependent: :destroy
	has_many :requests, dependent: :destroy
	has_many :comments, dependent: :destroy
	has_many :relationships, through: :active_relationships, source: :followed
	has_many :active_relationships, class_name: :Relationship.name,
    foreign_key: :follower_id, dependent: :destroy
	has_many :passive_relationships, class_name: :Relationship.name,
    foreign_key: :followed_id, dependent: :destroy
	has_many :following, through: :active_relationships, source: :followed
	before_save {self.email = email.downcase}
	has_secure_password
	validates :password,presence: true,length: {minimum: 6, allow_blank: true}
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, length: { maximum: 100 },
	format: {with: VALID_EMAIL_REGEX},uniqueness: {case_sensitive: false}
	VALID_FULLNAME_REGEX = /[\w]+([\s]+[\w]+){1}+/
	validates :fullname,presence: true, length: {maximum:150},
	format: {with: VALID_FULLNAME_REGEX}

  def follow(other_user)
  	active_relationships.create(followed_id: other_user.id)
  end

  def unfollow(other_user)
  	active_relationships.find_by(followed_id: other_user.id).destroy
  end

  def count_fl
  	active_relationships.find_by(followed_id: other_user.id).count
  end

  def following?(other_user)
  	following.include?(other_user)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :book_load, only: [:index, :edit, :update, :destroy ]

  def index
    @books=Book.paginate page: params[:page],per_page: Settings.ten
  end

  def show
    @book=book_load
    @reviews=@book.review
    @rating=@book.rating
  end

  def new
    @categories=Category.all
  end

  def create
    book = Book.new book_params
    if book.save
      flash[:success] = t "success_create"
      redirect_to books_path
    else
      flash[:info] = t "error_create"
      render "new"
    end
  end

  def edit
    @book = book_load
  end

  def update
    book = book_load
    if book.update_attributes(book_params)
      flash[:success] = t "update_success"
      redirect_to books_path
    else
      flash[:error] = t "update_error"
      render :back
    end
  end

  def destroy
    book_load.destroy
    flash[:success] = t "delete_success"
    redirect_to books_path
  end

  private
  def book_params
    params.require(:book).permit(:title,:publish_date,:author,:num_of_page,:category_id,:image,rating:0)
  end

  def book_load
    book = Book.find_by params[:id]
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
	def index
		@reviews =Review.paginate(page: params[:page],per_page: 5)
	end

	def update
		@book = review_load.book
		if review_load.update_attributes(params_update)
			flash[:success] = "Success for Update!"
      redirect_to @book
    else
			flash[:success] = "Error for Update!"
      redirect_to :back
    end
	end

	def edit
		@review=review_load
	end
	def create
		@review = Review.new(review_params)
		if @review.save
			flash[:success] = "Success for Create!"
			book=Book.find(@review.book_id)
			redirect_to book
		else
			flash[:info] = "Error for Create!"
			render 'new'
		end
	end

	def show
		@review=Review.find(params[:id])
		@comments = @review.comments
	end

	def new
		@book_id=params[:book_id]
	end

	def destroy
		@book= Book.find(review_load.book_id)
		review_load.destroy
		flash[:success] = "Delete success!"
		redirect_to @book
	end


	private
	def review_params
		params.require(:review).permit(:title,:content,:book_id,:user_id)
	end
	def params_update
		params.require(:review).permit(:title,:content)
	end
	def review_load
		review = Review.find(params[:id])
	end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
  def check_rate book_id,condition
    active=Activity.where(user_id:current_user.id,target_id:book_id,action:condition)
    return active.any?
  end

  def avg_rating book_id
    return count_rating=Activity.where(action: t("rating"),target_id:book_id,target_type:"book").count+1
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
  def like target_id,user_id
    return Like.where(target_id:target_id,user_id:user_id).any?
  end

  def toggle_like_button(activity,user)
    if Like.where(target_id:activity.id,user_id:current_user.id).any?
      link_to " DisLike",like_path(id:activity.id,user_id:user.id),method: "delete",remote:true,class: "fa fa-thumbs-o-down",id:"dis#{activity.id}"
    else
      link_to " Like",likes_path(id:activity.id,user_id:user.id),remote:true,class: "fa fa-thumbs-o-up",id:"like#{activity.id}"
    end
  end
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
  def Request_Toggle request
    unless current_user.is_admin
      unless request.status
        link_to t("cancel"), request_path(id:request.id), method: "delete",
          class: "fa fa-check",data: {confirm: t("confirm")}
      end
    end
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def user_login user
    session[:user_id] = user.id
  end

  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find(user_id)
    end
  end

  def login?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  def is_admin?
    return current_user.is_admin
  end
end

app/helpers/users_helper.rb
module UsersHelper
	# Returns the Gravatar for the given user.
	def gravatar_for human,size=200
		gravatar_id = Digest::MD5::hexdigest(human.email.downcase)
		gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
		image_tag(gravatar_url, alt: human.fullname, class: "gravatar")
	end
end

app/views/reviews/_list_review.html.erb
<div class="product-collateral">
<h1><%= link_to "List Review",reviews_path %></h1>
<div class="box-collateral box-description">
<h2>
<% @reviews.each do |item| %>
<%= link_to item.title,item %>
	<p><%= item.content %></p></p>
<hr>
<% end %>
</h2>
</div>
</div>

app/views/reviews/edit.html.erb
<div class="inner_page">
<div class="signup">
<h1>New Review</h1><br>
		<%= form_for(@review) do |f| %>
		<%= render 'shared/error_messages', object: f.object %>
		<div class="form-group">
			<%= f.text_field :title, placeholder: "Title", :class => "input-text" %>
			<%= f.hidden_field :book_id, value: @book_id, :class => "input-text" %>
			<%= f.hidden_field :user_id,:value=>current_user.id %>
		</div>
		<div class="form-group">
			<%= f.text_area :content, placeholder: "Content", :class => "area-text" %>
		</div>
		<div class="form-group">
			<button type="submit" class="btn btn-submit">Update Review</button>
		</div>
		<% end %>

	</div>
</div>

app/views/reviews/index.html.erb
<%= render "list_review" %>
<%= will_paginate @reviews %>
<input name="star1" type="radio" class="star"/>
<input name="star1" type="radio" class="star"/>
<input name="star1" type="radio" class="star"/>
<input name="star1" type="radio" class="star"/>
<input name="star1" type="radio" class="star"/>

app/views/reviews/new.html.erb
<div class="inner_page">
<div class="signup">
<h1>New Review</h1><br>
		<%= form_for(Review.new) do |f| %>
		<%= render 'shared/error_messages', object: f.object %>
		<div class="form-group">
			<%= f.text_field :title, placeholder: "Title", :class => "input-text" %>
			<%= f.hidden_field :book_id, value: @book_id, :class => "input-text" %>
			<%= f.hidden_field :user_id,:value=>current_user.id %>
		</div>
		<div class="form-group">
			<%= f.text_area :content, placeholder: "Content", :class => "area-text" %>
		</div>
		<div class="form-group">
			<button type="submit" class="btn btn-submit">Create Review</button>
		</div>  
		<% end %>

	</div>
</div>

app/views/reviews/show.html.erb
<div class="review">
	<h1><%= @review.title %></h1>
	<% if(login? && current_user.id==@review.user_id) %>
	<div class="review-edit">
		<%= link_to "<label for='file-upload' class='custom-file-upload'>
					<i class='fa fa-pencil'></i> Edit
		</label></a>".html_safe,edit_review_path(@review.id) %>
		&nbsp;&nbsp;|&nbsp;&nbsp;
		<%= link_to "<label for='file-upload' class='custom-file-upload'>
					<i class='fa fa-trash'></i> Delete
		</label></a>".html_safe,review_path(@review.id),method: "delete",data: { confirm: 'Are you sure?' }  %>
	</div>
	<% end %>
	<hr>
	<dir><%= @review.content %></dir>
	<hr>
	<div class="comment">
		<div id="comment-form">
      <%= render "comments/form" %>
    </div>
		<div id="comments-list">
      <%= render @comments %>
    </div>
	</div>
</div>